import type { DaemonConfig } from './config.js';
import type { CancelDurableRunResult, DaemonEventInput, DaemonStatus, FollowUpDurableRunResult, GetDurableRunResult, ListDurableRunsResult, ListRecoverableWebLiveConversationRunsResult, ReplayDurableRunResult, StartBackgroundRunRequestInput, StartBackgroundRunResult, StartScheduledTaskRunResult, SyncWebLiveConversationRunRequestInput, SyncWebLiveConversationRunResult } from './types.js';
export declare function pingDaemon(config?: DaemonConfig): Promise<boolean>;
export declare function getDaemonStatus(config?: DaemonConfig): Promise<DaemonStatus>;
export declare function stopDaemon(config?: DaemonConfig): Promise<void>;
export declare function listDurableRuns(config?: DaemonConfig): Promise<ListDurableRunsResult>;
export declare function getDurableRun(runId: string, config?: DaemonConfig): Promise<GetDurableRunResult>;
export declare function startScheduledTaskRun(taskId: string, config?: DaemonConfig): Promise<StartScheduledTaskRunResult>;
export declare function startBackgroundRun(input: StartBackgroundRunRequestInput, config?: DaemonConfig): Promise<StartBackgroundRunResult>;
export declare function cancelDurableRun(runId: string, config?: DaemonConfig): Promise<CancelDurableRunResult>;
export declare function rerunDurableRun(runId: string, config?: DaemonConfig): Promise<ReplayDurableRunResult>;
export declare function followUpDurableRun(runId: string, prompt?: string, config?: DaemonConfig): Promise<FollowUpDurableRunResult>;
export declare function syncWebLiveConversationRunState(input: SyncWebLiveConversationRunRequestInput, config?: DaemonConfig): Promise<SyncWebLiveConversationRunResult>;
export declare function listRecoverableWebLiveConversationRunsFromDaemon(config?: DaemonConfig): Promise<ListRecoverableWebLiveConversationRunsResult>;
export declare function emitDaemonEvent(input: DaemonEventInput, config?: DaemonConfig): Promise<boolean>;
export declare function emitDaemonEventNonFatal(input: DaemonEventInput, config?: DaemonConfig): Promise<void>;
