#!/usr/bin/env node
export type { AutomationActivityEntry, AutomationActivityKind, AutomationActivityOutcome, AutomationConversationBehavior, AutomationMutationInput, AutomationSchedulerState, AutomationTargetType, AutomationThreadMode, LegacyAutomationImportIssue, StoredAutomation, } from './automation-store.js';
export { appendAutomationActivityEntry, closeAutomationDbs, createStoredAutomation, deleteStoredAutomation, ensureLegacyTaskImports, getAutomationDbPath, getStoredAutomation, listAutomationActivityEntries, listStoredAutomations, loadAutomationRuntimeStateMap, loadAutomationSchedulerState, saveAutomationRuntimeStateMap, saveAutomationSchedulerState, setStoredAutomationThreadBinding, updateStoredAutomation, } from './automation-store.js';
export { normalizeAutomationTargetTypeForSelection } from './automation-store.js';
export { ensureAutomationThread, normalizeAutomationThreadModeForSelection, resolveAutomationThreadTitle } from './automation-threads.js';
export { type BackgroundRunAgentSpec, buildBackgroundAgentArgv, looksLikePersonalAgentCliEntryPath } from './background-run-agent.js';
export { cancelDurableRun, emitDaemonEvent, emitDaemonEventNonFatal, followUpDurableRun, getDaemonStatus, getDurableRun, listDurableRuns, listRecoverableWebLiveConversationRunsFromDaemon, pingDaemon, rerunDurableRun, startBackgroundRun, startScheduledTaskRun, stopDaemon, syncWebLiveConversationRunState, } from './client.js';
export { getCompanionRuntimeProvider, resolveCompanionRuntime, setCompanionRuntimeProvider } from './companion/runtime.js';
export type { CompanionRuntime, CompanionRuntimeProvider } from './companion/types.js';
export { type DaemonConfig, getDaemonConfigFilePath, getDefaultDaemonConfig, loadDaemonConfig } from './config.js';
export { buildDeferredResumeActivityId, buildDeferredResumeAlertId, surfaceReadyDeferredResume } from './conversation-wakeups.js';
export { createDaemonEvent, DAEMON_EVENT_VERSION, isDaemonEvent } from './events.js';
export { bindInProcessDaemonClient, clearDaemonClientTransportOverride, createInProcessDaemonClient, type DaemonClientTransport, getDaemonClientTransportOverride, setDaemonClientTransportOverride, } from './in-process-client.js';
export type { ParsedTaskDefinition } from './modules/tasks-parser.js';
export { parseTaskDefinition } from './modules/tasks-parser.js';
export { resolveDaemonPaths } from './paths.js';
export { type BackgroundRunResultSummary, listPendingBackgroundRunResults, markBackgroundRunResultsDelivered, surfaceBackgroundRunResultsIfReady, } from './runs/background-run-deferred-resumes.js';
export { createBackgroundRunId, createBackgroundRunRecord, finalizeBackgroundRun, markBackgroundRunInterrupted, markBackgroundRunStarted, type StartBackgroundRunInput, type StartBackgroundRunRecord, } from './runs/background-runs.js';
export { cancelDeferredResumeConversationRun, completeDeferredResumeConversationRun, createDeferredResumeConversationRunId, markDeferredResumeConversationRunReady, markDeferredResumeConversationRunRetryScheduled, markDeferredResumeConversationRunSnoozed, scheduleDeferredResumeConversationRun, } from './runs/deferred-resume-conversations.js';
export type { DurableRunCheckpointFile, DurableRunEvent, DurableRunKind, DurableRunManifest, DurableRunPaths, DurableRunRecoveryAction, DurableRunResumePolicy, DurableRunStatus, DurableRunStatusFile, ScannedDurableRun, ScannedDurableRunsSummary, } from './runs/store.js';
export { appendDurableRunEvent, createDurableRunManifest, createInitialDurableRunStatus, listDurableRunIds, loadDurableRunCheckpoint, loadDurableRunManifest, loadDurableRunStatus, readDurableRunEvents, resolveDurableRunPaths, resolveDurableRunsRoot, saveDurableRunCheckpoint, saveDurableRunManifest, saveDurableRunStatus, scanDurableRun, scanDurableRunsForRecovery, summarizeScannedDurableRuns, } from './runs/store.js';
export type { RecoverableWebLiveConversationRun, WebLiveConversationPendingOperation, WebLiveConversationPreludeMessage, WebLiveConversationPromptImage, WebLiveConversationRunState, } from './runs/web-live-conversations.js';
export { createWebLiveConversationRunId, listRecoverableWebLiveConversationRuns, parsePendingOperation, saveWebLiveConversationRunState, } from './runs/web-live-conversations.js';
export { type DaemonStopRequestBehavior, PersonalAgentDaemon, type PersonalAgentDaemonOptions } from './server.js';
export { readTailscaleServeProxyState, resolveTailscaleServeBaseUrl, syncTailscaleServeProxy, type SyncTailscaleServeProxyInput, type TailscaleServeProxyState, type TailscaleServeProxyStatus, } from './tailscale-serve.js';
export type { CancelDurableRunResult, DaemonEvent, DaemonEventInput, DaemonModuleStatus, DaemonStatus, FollowUpDurableRunResult, GetDurableRunResult, ListDurableRunsResult, ListRecoverableWebLiveConversationRunsResult, ReplayDurableRunResult, StartBackgroundRunRequestInput, StartBackgroundRunResult, StartScheduledTaskRunResult, SyncWebLiveConversationRunRequestInput, SyncWebLiveConversationRunResult, } from './types.js';
export declare function runDaemonCli(argv?: string[]): Promise<number>;
