import { type DaemonConfig } from './config.js';
import { type StartBackgroundRunInput } from './runs/background-runs.js';
import type { CancelDurableRunResult, DaemonEvent, DaemonStatus, FollowUpDurableRunResult, GetDurableRunResult, ListDurableRunsResult, ListRecoverableWebLiveConversationRunsResult, ReplayDurableRunResult, StartBackgroundRunResult, StartScheduledTaskRunResult, SyncWebLiveConversationRunRequestInput, SyncWebLiveConversationRunResult } from './types.js';
export type DaemonStopRequestBehavior = 'exit-process' | 'reject' | 'stop-only';
export interface PersonalAgentDaemonOptions {
    config?: DaemonConfig;
    stopRequestBehavior?: DaemonStopRequestBehavior;
    logSink?: (line: string) => void;
}
export declare class PersonalAgentDaemon {
    private readonly config;
    private readonly paths;
    private readonly runsRoot;
    private readonly bus;
    private readonly startedAt;
    private readonly pid;
    private readonly modules;
    private readonly stopRequestBehavior;
    private readonly logSink?;
    private readonly activeBackgroundRuns;
    private readonly socketTraces;
    private server?;
    private timerHandles;
    private running;
    private stopping;
    constructor(input?: DaemonConfig | PersonalAgentDaemonOptions);
    getSocketPath(): string;
    start(): Promise<void>;
    stop(): Promise<void>;
    isRunning(): boolean;
    getStatus(): DaemonStatus;
    private prepareSocket;
    private createModuleContext;
    private registerModuleSubscriptions;
    private registerModuleTimers;
    private attachConnection;
    private getSocketTrace;
    private formatSocketTrace;
    private handleSocketError;
    private respond;
    private handleLine;
    private handleRequest;
    requestStop(): Promise<{
        stopping: boolean;
    }>;
    publishEvent(event: DaemonEvent): boolean;
    listDurableRuns(): ListDurableRunsResult;
    getDurableRun(runId: string): GetDurableRunResult | undefined;
    private waitForScheduledRunRecord;
    startScheduledTaskRun(taskId: string): Promise<StartScheduledTaskRunResult>;
    private surfaceBackgroundRunResults;
    private surfaceBackgroundRunOutcome;
    private finalizeBackgroundRunStartFailure;
    private spawnBackgroundRun;
    startBackgroundRun(input: StartBackgroundRunInput): Promise<StartBackgroundRunResult>;
    private getReplayableBackgroundRun;
    rerunBackgroundRun(runId: string): Promise<ReplayDurableRunResult>;
    followUpBackgroundRun(runId: string, prompt?: string): Promise<FollowUpDurableRunResult>;
    cancelBackgroundRun(runId: string, reason?: string): Promise<CancelDurableRunResult>;
    private recoverInterruptedBackgroundRuns;
    syncWebLiveConversationRun(input: SyncWebLiveConversationRunRequestInput): Promise<SyncWebLiveConversationRunResult>;
    listRecoverableWebLiveConversationRuns(): ListRecoverableWebLiveConversationRunsResult;
    private logDurableRunRecoverySummary;
    private log;
}
export declare function runDaemonProcess(): Promise<void>;
