/**
 * AppsPage — top-level page for skill apps.
 *
 * Shows app cards in a grid. Click an app to load and interact with it.
 */

import { useCallback, useEffect, useState } from 'react';

import { AppPageIntro, AppPageLayout } from '../components/ui';
import { AppPageViewer } from './AppPageViewer';
import type { SkillApp } from './types';
import { useAppList } from './useAppList';

export function AppsPage() {
  const { apps, loading, error } = useAppList();
  const [selectedApp, setSelectedApp] = useState<SkillApp | null>(null);
  const [pageContent, setPageContent] = useState<string | null>(null);
  const [pageLoading, setPageLoading] = useState(false);
  const [pageError, setPageError] = useState<string | null>(null);

  const handleSelectApp = useCallback((app: SkillApp) => {
    setSelectedApp(app);
  }, []);

  const handleBack = useCallback(() => {
    setSelectedApp(null);
    setPageContent(null);
    setPageError(null);
  }, []);

  // Fetch page content when an app is selected
  useEffect(() => {
    if (!selectedApp) {
      setPageContent(null);
      setPageError(null);
      return;
    }

    let cancelled = false;
    setPageLoading(true);
    setPageContent(null);
    setPageError(null);

    fetch(`/api/vault/file?id=apps/${encodeURIComponent(selectedApp.name)}/${encodeURIComponent(selectedApp.entry)}`)
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load app page: ${res.statusText}`);
        return res.json() as Promise<{ content: string }>;
      })
      .then((data) => {
        if (cancelled) return;
        setPageContent(data.content);
        setPageLoading(false);
      })
      .catch((err: Error) => {
        if (cancelled) return;
        setPageError(err.message);
        setPageLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [selectedApp]);

  // Error state
  if (error) {
    return (
      <AppPageLayout>
        <div className="flex items-center justify-center px-6 py-20 text-center">
          <p className="text-[13px] text-danger">{error}</p>
        </div>
      </AppPageLayout>
    );
  }

  // Loading state
  if (loading) {
    return (
      <AppPageLayout>
        <div className="flex items-center justify-center px-6 py-20 text-center">
          <p className="text-[13px] text-dim">Loading apps…</p>
        </div>
      </AppPageLayout>
    );
  }

  // App page view
  if (selectedApp) {
    if (pageLoading) {
      return (
        <div className="flex h-full flex-col overflow-hidden">
          <div className="flex items-center gap-2 border-b border-border-subtle px-4 py-2">
            <button type="button" className="ui-toolbar-button px-2 py-1 text-[12px]" onClick={handleBack}>
              ← Back
            </button>
            <p className="text-[13px] font-medium text-primary">{selectedApp.name}</p>
          </div>
          <div className="flex flex-1 items-center justify-center px-6 text-center">
            <p className="text-[13px] text-dim">Loading app…</p>
          </div>
        </div>
      );
    }

    if (pageError || !pageContent) {
      return (
        <div className="flex h-full flex-col overflow-hidden">
          <div className="flex items-center gap-2 border-b border-border-subtle px-4 py-2">
            <button type="button" className="ui-toolbar-button px-2 py-1 text-[12px]" onClick={handleBack}>
              ← Back
            </button>
            <p className="text-[13px] font-medium text-primary">{selectedApp.name}</p>
          </div>
          <div className="flex flex-1 items-center justify-center px-6 text-center">
            <p className="text-[13px] text-danger">{pageError ?? 'Could not load app page'}</p>
          </div>
        </div>
      );
    }

    return (
      <div className="flex h-full flex-col overflow-hidden">
        <div className="flex items-center gap-2 border-b border-border-subtle px-5 py-2">
          <button type="button" className="ui-toolbar-button px-2 py-1 text-[12px]" onClick={handleBack}>
            ← Back
          </button>
          <p className="text-[13px] font-medium text-primary">{selectedApp.name}</p>
        </div>
        <div className="min-h-0 flex-1">
          <AppPageViewer app={selectedApp} content={pageContent} />
        </div>
      </div>
    );
  }

  // Apps list grid
  return (
    <AppPageLayout>
      <AppPageIntro
        eyebrow="Apps"
        title="Skill Apps"
        summary={
          apps.length === 0
            ? 'No apps yet. Ask an agent to create one from a skill or prompt.'
            : 'Interactive UIs generated by agents from skills and prompts.'
        }
      />

      {apps.length === 0 ? (
        <div className="flex items-center justify-center px-6 py-16 text-center">
          <div className="max-w-sm">
            <p className="text-[13px] leading-6 text-secondary">
              Apps are stored in your knowledge base under <code className="rounded bg-surface px-1 py-0.5 text-[12px]">apps/</code>. Ask an
              agent to create one.
            </p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-3 px-5 pb-6 sm:grid-cols-2 lg:grid-cols-3">
          {apps.map((app) => (
            <button
              key={app.name}
              type="button"
              className="flex flex-col rounded-xl border border-border-subtle bg-surface p-4 text-left transition-colors hover:border-accent/30 hover:bg-surface-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/20"
              onClick={() => handleSelectApp(app)}
            >
              <p className="text-[13px] font-semibold text-primary">{app.name}</p>
              {app.description ? <p className="mt-1 text-[12px] leading-5 text-secondary line-clamp-2">{app.description}</p> : null}
              <div className="mt-3 flex items-center gap-2">
                <span className="rounded-full bg-accent/10 px-2 py-0.5 text-[10px] font-medium text-accent">
                  {app.nav.length > 1 ? `${app.nav.length} pages` : 'Single page'}
                </span>
                {app.prompt ? <span className="truncate font-mono text-[10px] text-dim">{app.prompt.slice(0, 40)}</span> : null}
              </div>
            </button>
          ))}
        </div>
      )}
    </AppPageLayout>
  );
}
