/**
 * AppsPage — top-level page for skill apps.
 *
 * Shows app cards in a grid. Click an app to load and interact with it.
 */

import { useCallback, useEffect, useState } from 'react';

import { AppPageIntro, AppPageLayout, ToolbarButton } from '../components/ui';
import { AppIcon } from './AppIcon';
import { AppPageViewer } from './AppPageViewer';
import type { SkillApp } from './types';
import { useAppList } from './useAppList';

export function AppsPage() {
  const { apps, loading, error } = useAppList();
  const [selectedApp, setSelectedApp] = useState<SkillApp | null>(null);
  const [pageContent, setPageContent] = useState<string | null>(null);
  const [pageLoading, setPageLoading] = useState(false);
  const [pageError, setPageError] = useState<string | null>(null);

  const handleSelectApp = useCallback((app: SkillApp) => {
    setSelectedApp(app);
  }, []);

  const handleBack = useCallback(() => {
    setSelectedApp(null);
    setPageContent(null);
    setPageError(null);
  }, []);

  // Fetch page content when an app is selected
  useEffect(() => {
    if (!selectedApp) {
      setPageContent(null);
      setPageError(null);
      return;
    }

    let cancelled = false;
    setPageLoading(true);
    setPageContent(null);
    setPageError(null);

    fetch(`/api/vault/file?id=apps/${encodeURIComponent(selectedApp.id)}/${encodeURIComponent(selectedApp.entry)}`)
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load app page: ${res.statusText}`);
        return res.json() as Promise<{ content: string }>;
      })
      .then((data) => {
        if (cancelled) return;
        setPageContent(data.content);
        setPageLoading(false);
      })
      .catch((err: Error) => {
        if (cancelled) return;
        setPageError(err.message);
        setPageLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [selectedApp]);

  // Error state
  if (error) {
    return (
      <div className="h-full overflow-y-auto">
        <AppPageLayout shellClassName="max-w-[72rem]">
          <AppPageIntro title="Apps" summary="Interactive UIs generated by agents from skills and prompts." />
          <div className="border-t border-border-subtle py-6 text-[14px] text-danger">{error}</div>
        </AppPageLayout>
      </div>
    );
  }

  // Loading state
  if (loading) {
    return (
      <div className="h-full overflow-y-auto">
        <AppPageLayout shellClassName="max-w-[72rem]">
          <AppPageIntro title="Apps" summary="Interactive UIs generated by agents from skills and prompts." />
          <div className="border-t border-border-subtle py-6 text-[14px] text-secondary">Loading apps…</div>
        </AppPageLayout>
      </div>
    );
  }

  // App page view
  if (selectedApp) {
    if (pageLoading) {
      return (
        <div className="h-full overflow-y-auto">
          <AppPageLayout shellClassName="max-w-[72rem]">
            <AppPageIntro
              title={selectedApp.name}
              summary="Loading app page…"
              actions={
                <ToolbarButton className="rounded-lg px-3 py-1.5 text-[12px] text-primary shadow-none" onClick={handleBack}>
                  Back
                </ToolbarButton>
              }
            />
            <div className="border-t border-border-subtle py-6 text-[14px] text-secondary">Loading app…</div>
          </AppPageLayout>
        </div>
      );
    }

    if (pageError || !pageContent) {
      return (
        <div className="h-full overflow-y-auto">
          <AppPageLayout shellClassName="max-w-[72rem]">
            <AppPageIntro
              title={selectedApp.name}
              summary="Could not load this app page. Tiny tragedy."
              actions={
                <ToolbarButton className="rounded-lg px-3 py-1.5 text-[12px] text-primary shadow-none" onClick={handleBack}>
                  Back
                </ToolbarButton>
              }
            />
            <div className="border-t border-border-subtle py-6 text-[14px] text-danger">{pageError ?? 'Could not load app page'}</div>
          </AppPageLayout>
        </div>
      );
    }

    return (
      <div className="flex h-full flex-col overflow-hidden">
        <div className="flex items-center gap-2 border-b border-border-subtle px-5 py-2">
          <button type="button" className="ui-toolbar-button px-2 py-1 text-[12px]" onClick={handleBack}>
            ← Back
          </button>
          <p className="text-[13px] font-medium text-primary">{selectedApp.name}</p>
        </div>
        <div className="min-h-0 flex-1">
          <AppPageViewer app={selectedApp} content={pageContent} />
        </div>
      </div>
    );
  }

  // Apps list grid
  return (
    <div className="h-full overflow-y-auto">
      <AppPageLayout shellClassName="max-w-[72rem]" contentClassName="space-y-10">
        <AppPageIntro
          title="Apps"
          summary={
            apps.length === 0
              ? 'No apps yet. Ask an agent to create one from a skill or prompt.'
              : 'Interactive UIs generated by agents from skills and prompts.'
          }
        />

        {apps.length === 0 ? (
          <div className="max-w-3xl border-t border-border-subtle py-6">
            <p className="text-[14px] leading-7 text-secondary">
              Apps are stored in your knowledge base under <code className="rounded bg-surface px-1 py-0.5 text-[12px]">apps/</code>. Ask an
              agent to create one.
            </p>
          </div>
        ) : (
          <section className="border-t border-border-subtle">
            {apps.map((app) => (
              <button
                key={app.id}
                type="button"
                className="group grid w-full gap-3 border-b border-border-subtle py-5 text-left text-primary transition-colors hover:text-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/25 focus-visible:ring-offset-2 focus-visible:ring-offset-base sm:grid-cols-[minmax(0,1fr)_auto] sm:items-start sm:gap-6"
                onClick={() => handleSelectApp(app)}
              >
                <div className="flex min-w-0 gap-3">
                  <AppIcon app={app} />
                  <div className="min-w-0 space-y-1.5">
                    <p className="truncate text-[15px] font-semibold tracking-tight text-primary transition-colors group-hover:text-accent">
                      {app.name}
                    </p>
                    {app.description ? (
                      <p className="max-w-3xl text-[13px] leading-6 text-secondary line-clamp-2">{app.description}</p>
                    ) : null}
                    {app.prompt ? <p className="truncate font-mono text-[11px] text-dim">{app.prompt.slice(0, 72)}</p> : null}
                  </div>
                </div>
                <div className="text-[12px] text-secondary sm:text-right">
                  <div>{app.nav.length > 1 ? `${app.nav.length} pages` : 'Single page'}</div>
                  <div className="mt-1 text-[11px] text-dim">Open app</div>
                </div>
              </button>
            ))}
          </section>
        )}
      </AppPageLayout>
    </div>
  );
}
