export { emitKBEvent, onKBEvent } from '../../../../../extensions/system-knowledge/src/components/knowledgeEvents';
export { VaultEditor } from '../../../../../extensions/system-knowledge/src/components/VaultEditor';
export { VaultFileTree } from '../../../../../extensions/system-knowledge/src/components/VaultFileTree';
export { knowledgeApi } from '../../../../../extensions/system-knowledge/src/lib/knowledgeApi';
export { getKnowledgeBaseSyncPresentation } from '../../../../../extensions/system-knowledge/src/lib/knowledgeBaseSyncStatus';
export { navigateKnowledgeFile } from '../../../../../extensions/system-knowledge/src/lib/knowledgeNavigation';
export { stripMarkdownFrontmatter } from '../../../../../extensions/system-knowledge/src/lib/markdownDocument';
export { buildMentionLookup, renderChildrenWithMentionLinks } from '../../../../../extensions/system-knowledge/src/lib/mentionRendering';
export type { NodeMentionSurface } from '../../../../../extensions/system-knowledge/src/lib/nodeMentionRoutes';
export { type ParsedSkillBlock, parseSkillBlock } from '../../../../../extensions/system-knowledge/src/lib/skillBlock';
