import { mkdirSync, writeFileSync } from 'fs';
import { basename, extname, join } from 'path';
import type { MemoryModuleConfig } from '../config.js';
import type { DaemonEvent } from '../types.js';
import { runCommand } from './command.js';
import type { DaemonModule, DaemonModuleContext } from './types.js';

interface MemoryModuleState {
  dirty: boolean;
  needsEmbedding: boolean;
  lastSummaryAt?: string;
  lastQmdUpdateAt?: string;
  lastQmdEmbedAt?: string;
  lastError?: string;
}

function toSessionSummaryFile(summaryDir: string, sessionFile: string): string {
  const base = basename(sessionFile, extname(sessionFile));
  return join(summaryDir, `${base}.md`);
}

function renderSummaryMarkdown(event: DaemonEvent, sessionFile: string): string {
  const profile = typeof event.payload.profile === 'string' ? event.payload.profile : 'unknown';
  const cwd = typeof event.payload.cwd === 'string' ? event.payload.cwd : 'unknown';

  return [
    `# Session ${basename(sessionFile)}`,
    '',
    `- event: ${event.type}`,
    `- updatedAt: ${event.timestamp}`,
    `- profile: ${profile}`,
    `- cwd: ${cwd}`,
    `- source: ${event.source}`,
    '',
    'Scaffold summary generated by personal-agentd memory module.',
    '',
  ].join('\n');
}

async function ensureCollections(config: MemoryModuleConfig, context: DaemonModuleContext): Promise<void> {
  for (const collection of config.collections) {
    const result = await runCommand('qmd', ['collection', 'add', collection.path, '--name', collection.name]);

    if (result.code !== 0) {
      const stderr = result.stderr.toLowerCase();
      const alreadyExists = stderr.includes('exists') || stderr.includes('already');
      if (!alreadyExists) {
        context.logger.warn(`qmd collection add failed for ${collection.name}: ${result.stderr || 'unknown error'}`);
      }
    }
  }
}

async function runQmdUpdate(config: MemoryModuleConfig, context: DaemonModuleContext): Promise<void> {
  const result = await runCommand('qmd', ['update', '--index', config.qmd.index]);
  if (result.code !== 0) {
    throw new Error(result.stderr || 'qmd update failed');
  }

  context.publish('memory.qmd.update.completed', {
    index: config.qmd.index,
    at: new Date().toISOString(),
  });
}

async function runQmdEmbed(config: MemoryModuleConfig, context: DaemonModuleContext): Promise<void> {
  const result = await runCommand('qmd', ['embed', '--index', config.qmd.index]);
  if (result.code !== 0) {
    throw new Error(result.stderr || 'qmd embed failed');
  }

  context.publish('memory.qmd.embed.completed', {
    index: config.qmd.index,
    at: new Date().toISOString(),
  });
}

export function createMemoryModule(config: MemoryModuleConfig): DaemonModule {
  const state: MemoryModuleState = {
    dirty: false,
    needsEmbedding: false,
  };

  return {
    name: 'memory',
    enabled: config.enabled,
    subscriptions: [
      'session.updated',
      'session.closed',
      'memory.reindex.requested',
      'timer.memory.qmd.update',
      'timer.memory.qmd.embed',
    ],
    timers: [
      {
        name: 'memory-qmd-update',
        eventType: 'timer.memory.qmd.update',
        intervalMs: Math.max(5_000, config.qmd.updateDebounceSeconds * 1000),
      },
      {
        name: 'memory-qmd-embed',
        eventType: 'timer.memory.qmd.embed',
        intervalMs: Math.max(30_000, config.qmd.embedDebounceSeconds * 1000),
      },
    ],

    async start(context): Promise<void> {
      mkdirSync(config.summaryDir, { recursive: true, mode: 0o700 });

      try {
        await ensureCollections(config, context);
      } catch (error) {
        state.lastError = (error as Error).message;
        context.logger.warn(`memory module startup warning: ${state.lastError}`);
      }
    },

    async handleEvent(event, context): Promise<void> {
      if (event.type === 'session.updated' || event.type === 'session.closed') {
        const sessionFile = event.payload.sessionFile;
        if (typeof sessionFile !== 'string' || sessionFile.length === 0) {
          return;
        }

        const summaryPath = toSessionSummaryFile(config.summaryDir, sessionFile);
        writeFileSync(summaryPath, renderSummaryMarkdown(event, sessionFile));

        state.dirty = true;
        state.needsEmbedding = true;
        state.lastSummaryAt = new Date().toISOString();
        state.lastError = undefined;

        context.publish('memory.summary.updated', {
          sessionFile,
          summaryPath,
        });

        return;
      }

      if (event.type === 'memory.reindex.requested') {
        state.dirty = true;
        state.needsEmbedding = true;
        return;
      }

      if (event.type === 'timer.memory.qmd.update') {
        if (!state.dirty) {
          return;
        }

        try {
          await runQmdUpdate(config, context);
          state.dirty = false;
          state.lastQmdUpdateAt = new Date().toISOString();
          state.lastError = undefined;
        } catch (error) {
          state.lastError = (error as Error).message;
          context.logger.warn(`memory module qmd update failed: ${state.lastError}`);
        }

        return;
      }

      if (event.type === 'timer.memory.qmd.embed') {
        if (!state.needsEmbedding) {
          return;
        }

        try {
          await runQmdEmbed(config, context);
          state.needsEmbedding = false;
          state.lastQmdEmbedAt = new Date().toISOString();
          state.lastError = undefined;
        } catch (error) {
          state.lastError = (error as Error).message;
          context.logger.warn(`memory module qmd embed failed: ${state.lastError}`);
        }
      }
    },

    getStatus(): Record<string, unknown> {
      return {
        dirty: state.dirty,
        needsEmbedding: state.needsEmbedding,
        lastSummaryAt: state.lastSummaryAt,
        lastQmdUpdateAt: state.lastQmdUpdateAt,
        lastQmdEmbedAt: state.lastQmdEmbedAt,
        lastError: state.lastError,
      };
    },
  };
}
