export type AskUserQuestionAnswers = unknown;
export type AskUserQuestionPresentation = unknown;
export type AppTelemetryEventRow = unknown;
export type AutoModeSummary = unknown;
export type CacheEfficiencyAggregate = unknown;
export type ContextPointerUsageResult = unknown;
export type ExtensionInstallSummary = unknown;
export type GatewayConnection = unknown;
export type GatewayEvent = unknown;
export type GatewayState = unknown;
export type GatewayThreadBinding = unknown;
export type KnowledgeBaseState = unknown;
export type MemoryDocItem = unknown;
export type MentionItem = unknown;
export type ScheduledTaskSchedulerHealth = unknown;
export type ScheduledTaskSummary = unknown;
export type SessionMeta = unknown;
export type SystemPromptAggregate = unknown;
export type ToolFlowResult = unknown;
export type TraceAgentLoop = unknown;
export type TraceCompactionAggs = unknown;
export type TraceCompactionEvent = unknown;
export type TraceContextSession = unknown;
export type TraceModelUsage = unknown;
export type TraceThroughput = unknown;
export type TraceTokenDaily = unknown;
export type TraceToolHealth = unknown;
export type VaultBacklink = unknown;
export type VaultBacklinksResult = unknown;
export type VaultEntry = unknown;
export type VaultFileContent = unknown;
export type VaultFileListResult = unknown;
export type VaultFileSummary = unknown;
export type VaultImageUploadResult = unknown;
export type VaultSearchResponse = unknown;
export type VaultShareImportResult = unknown;
export type VaultTreeResult = unknown;

export declare const CONVERSATION_LAYOUT_CHANGED_EVENT: string;
export declare const api: unknown;
export declare function useAppData(...args: never[]): unknown;
export declare function notifyExtensionRegistryChanged(...args: never[]): void;
export declare function readConversationLayout(...args: never[]): unknown;
export declare function timeAgo(...args: never[]): string;
export declare function timeAgoCompact(...args: never[]): string;
