export type HostComponent = (...args: never[]) => unknown;
export type AutoModeSummary = unknown;
export type CacheEfficiencyAggregate = unknown;
export type ContextPointerUsageResult = unknown;
export type GatewayConnection = unknown;
export type GatewayEvent = unknown;
export type GatewayState = unknown;
export type GatewayThreadBinding = unknown;
export type MemoryDocItem = unknown;
export type SessionMeta = unknown;
export type SystemPromptAggregate = unknown;
export type ToolFlowResult = unknown;
export type TraceAgentLoop = unknown;
export type TraceCompactionAggs = unknown;
export type TraceCompactionEvent = unknown;
export type TraceContextSession = unknown;
export type TraceModelUsage = unknown;
export type TraceThroughput = unknown;
export type TraceTokenDaily = unknown;
export type TraceToolHealth = unknown;
export type VaultFileSummary = unknown;

export declare const CONVERSATION_LAYOUT_CHANGED_EVENT: string;
export declare const VaultEditor: HostComponent;
export declare const VaultFileTree: HostComponent;
export declare const api: unknown;
export declare function useAppData(...args: never[]): unknown;
export declare function getKnowledgeBaseSyncPresentation(...args: never[]): unknown;
export declare function navigateKnowledgeFile(...args: never[]): unknown;
export declare function readConversationLayout(...args: never[]): unknown;
export declare function timeAgoCompact(...args: never[]): string;
