export type HostComponent = (...args: never[]) => unknown;
export type DesktopKnowledgeEntryContextMenuAction = unknown;
export type KnowledgeBaseState = unknown;
export type MentionItem = unknown;
export type VaultBacklink = unknown;
export type VaultBacklinksResult = unknown;
export type VaultEntry = unknown;
export type VaultFileContent = unknown;
export type VaultFileListResult = unknown;
export type VaultImageUploadResult = unknown;
export type VaultSearchResponse = unknown;
export type VaultShareImportResult = unknown;
export type VaultTreeResult = unknown;

export declare const ContextMenuWrapper: HostComponent;
export declare const KNOWLEDGE_OPEN_FILE_IDS_STORAGE_KEY: string;
export declare const KNOWLEDGE_TREE_EXPANDED_FOLDERS_STORAGE_KEY: string;
export declare const api: unknown;
export declare const vaultApi: unknown;
export declare function addOpenFileId(...args: never[]): unknown;
export declare function buildApiPath(...args: never[]): string;
export declare function canDropAllPaths(...args: never[]): unknown;
export declare function collapseExpandedFolderIds(...args: never[]): unknown;
export declare function cx(...values: Array<unknown>): string;
export declare function getDesktopBridge(...args: never[]): unknown;
export declare function getTopLevelDraggedPaths(...args: never[]): unknown;
export declare function normalizeOpenFileIds(...args: never[]): unknown;
export declare function readStoredExpandedFolderIds(...args: never[]): unknown;
export declare function readStoredOpenFileIds(...args: never[]): unknown;
export declare function readStoredRecentlyClosedFileIds(...args: never[]): unknown;
export declare function recordRecentlyClosedFileId(...args: never[]): unknown;
export declare function renameExpandedFolderIds(...args: never[]): unknown;
export declare function removeOpenFileId(...args: never[]): unknown;
export declare function renameOpenFileIds(...args: never[]): unknown;
export declare function shouldUseNativeAppContextMenus(...args: never[]): unknown;
export declare function useApi(...args: never[]): unknown;
export declare function useFileTreeModel(...args: never[]): unknown;
export declare function useInvalidateOnTopics(...args: never[]): unknown;
export declare function writeStoredExpandedFolderIds(...args: never[]): unknown;
export declare function writeStoredOpenFileIds(...args: never[]): unknown;
export declare function writeStoredRecentlyClosedFileIds(...args: never[]): unknown;
