export type HostComponent = (...args: never[]) => unknown;
export type AppTelemetryLogBundleExport = unknown;
export type AppTelemetryLogDiagnostics = unknown;
export type DesktopAppPreferencesState = unknown;
export type DesktopEnvironmentState = unknown;
export type ModelEditorDraft = unknown;
export type ModelProviderApi = unknown;
export type ModelProviderConfig = unknown;
export type ModelProviderModelConfig = unknown;
export type ModelProviderState = unknown;
export type ModelState = unknown;
export type ProviderAuthSummary = unknown;
export type ProviderEditorDraft = unknown;
export type ProviderOAuthLoginState = unknown;
export type ProviderOAuthLoginStreamEvent = unknown;
export interface ColorTheme {
  id: string;
  label: string;
  appearance: 'light' | 'dark';
  tokens?: Record<string, string>;
  extensionId?: string;
}
export type ThemePreference = 'light' | 'dark' | 'system';
export type TranscriptionModelStatus = unknown;
export type TranscriptionProviderId = unknown;
export type UnifiedSettingsEntry = unknown;

export declare const DesktopCompanionSettingsPanel: HostComponent;
export declare const DesktopConnectionsSettingsPanel: HostComponent; // App behavior panel
export declare const DesktopKeyboardShortcutsSettingsSection: HostComponent;
export declare const SettingsPage: HostComponent;
export declare const AppPageIntro: HostComponent;
export declare const AppPageLayout: HostComponent;
export declare const AppPageSection: HostComponent;
export declare const AppPageToc: HostComponent;
export declare const Pill: HostComponent;
export declare const THINKING_LEVEL_OPTIONS: unknown;
export declare const ToolbarButton: HostComponent;
export declare const api: unknown;
export declare function cx(...values: Array<unknown>): string;
export declare function createDesktopAwareEventSource(...args: never[]): unknown;
export declare function createModelEditorDraft(...args: never[]): unknown;
export declare function createProviderEditorDraft(...args: never[]): unknown;
export declare function formatCompanionTimestamp(...args: never[]): unknown;
export declare function formatContextWindowLabel(...args: never[]): unknown;
export declare function formatThinkingLevelLabel(...args: never[]): unknown;
export declare function getDesktopBridge(...args: never[]): unknown;
export declare function getModelSelectableServiceTierOptions(...args: never[]): unknown;
export declare function groupModelsByProvider(...args: never[]): unknown;
export declare function isDesktopShell(...args: never[]): unknown;
export declare function parseOptionalJsonObject(...args: never[]): unknown;
export declare function parseOptionalNonNegativeNumber(...args: never[]): unknown;
export declare function parseOptionalPositiveInteger(...args: never[]): unknown;
export declare function parseOptionalStringRecord(...args: never[]): unknown;
export declare function readDesktopEnvironment(...args: never[]): unknown;
export declare function resetStoredConversationUiState(...args: never[]): unknown;
export declare function resetStoredLayoutPreferences(...args: never[]): unknown;
export declare function subscribeDesktopProviderOAuthLogin(...args: never[]): unknown;
export declare function useApi(...args: never[]): unknown;
export declare function useInvalidateOnTopics(...args: never[]): unknown;
export declare function useTheme(): {
  theme: string;
  themePreference: ThemePreference;
  lightTheme: string;
  darkTheme: string;
  availableThemes: ColorTheme[];
  setThemePreference: (theme: ThemePreference) => void;
  setLightTheme: (theme: string) => void;
  setDarkTheme: (theme: string) => void;
  toggle: () => void;
};
