export type { ExtensionSurfaceProps } from './index.js';

export type HostComponent = (...args: never[]) => unknown;
export type DesktopKnowledgeEntryContextMenuAction = unknown;

export declare const AppPageEmptyState: HostComponent;
export declare const AppPageIntro: HostComponent;
export declare const AppPageLayout: HostComponent;
export declare const AppPageSection: HostComponent;
export declare const AppPageToc: HostComponent;
export declare const CheckpointInlineDiff: (...args: never[]) => unknown;
export declare const ContextMenuWrapper: HostComponent;
export declare const EmptyState: HostComponent;
export declare const ErrorState: HostComponent;
export declare const IconButton: HostComponent;
export declare const LoadingState: HostComponent;
export declare const Pill: HostComponent;
export declare const SurfacePanel: (...args: never[]) => unknown;
export declare const ToolbarButton: HostComponent;
export declare const KNOWLEDGE_OPEN_FILE_IDS_STORAGE_KEY: string;
export declare const KNOWLEDGE_TREE_EXPANDED_FOLDERS_STORAGE_KEY: string;
export declare function addOpenFileId(...args: never[]): unknown;
export declare function buildApiPath(...args: never[]): string;
export declare function createDesktopAwareEventSource(...args: never[]): unknown;
export declare function canDropAllPaths(...args: never[]): unknown;
export declare function collapseExpandedFolderIds(...args: never[]): unknown;
export declare function cx(...values: Array<unknown>): string;
export declare function getDesktopBridge(...args: never[]): unknown;
export declare function getTopLevelDraggedPaths(...args: never[]): unknown;
export declare function lazyRouteWithRecovery(...args: never[]): unknown;
export declare function normalizeOpenFileIds(...args: never[]): unknown;
export declare function readStoredExpandedFolderIds(...args: never[]): unknown;
export declare function readStoredOpenFileIds(...args: never[]): unknown;
export declare function readStoredRecentlyClosedFileIds(...args: never[]): unknown;
export declare function recordRecentlyClosedFileId(...args: never[]): unknown;
export declare function removeOpenFileId(...args: never[]): unknown;
export declare function renameExpandedFolderIds(...args: never[]): unknown;
export declare function renameOpenFileIds(...args: never[]): unknown;
export declare function shouldUseNativeAppContextMenus(...args: never[]): unknown;
export declare function useApi(...args: never[]): unknown;
export declare function useFileTreeModel(...args: never[]): unknown;
export declare function useInvalidateOnTopics(...args: never[]): unknown;
export declare function writeStoredExpandedFolderIds(...args: never[]): unknown;
export declare function writeStoredOpenFileIds(...args: never[]): unknown;
export declare function writeStoredRecentlyClosedFileIds(...args: never[]): unknown;
