#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import re
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
ASSETS_DIR = SKILL_DIR / "assets"
CSS_PATH = ASSETS_DIR / "latex.css"
FONTS_DIR = ASSETS_DIR / "fonts"
TEMPLATE_PATH = ASSETS_DIR / "report-template.html"

FONT_SETS = {
    "minimal": [
        ("Latin Modern", "normal", "normal", "LM-regular.woff2"),
    ],
    "full": [
        ("Latin Modern", "normal", "normal", "LM-regular.woff2"),
        ("Latin Modern", "italic", "normal", "LM-italic.woff2"),
        ("Latin Modern", "normal", "bold", "LM-bold.woff2"),
        ("Latin Modern", "italic", "bold", "LM-bold-italic.woff2"),
    ],
}


def strip_font_faces(css: str) -> str:
    return re.sub(r"@font-face\s*\{.*?\}\s*", "", css, flags=re.S)


def inline_font_face(font_family: str, font_style: str, font_weight: str, filename: str) -> str:
    font_path = FONTS_DIR / filename
    data = base64.b64encode(font_path.read_bytes()).decode("ascii")
    return f"""
@font-face {{
  font-family: '{font_family}';
  font-style: {font_style};
  font-weight: {font_weight};
  font-display: swap;
  src: url('data:font/woff2;base64,{data}') format('woff2');
}}
""".strip()


def build_template(font_set: str) -> str:
    css = strip_font_faces(CSS_PATH.read_text())
    font_css = "\n\n".join(
        inline_font_face(font_family, font_style, font_weight, filename)
        for font_family, font_style, font_weight, filename in FONT_SETS[font_set]
    )

    extra_css = """
.keywords { font-size: 0.92rem; margin-top: 0.8rem; }
.no-indent { text-indent: 0; }
svg { width: 100%; height: auto; display: block; }
svg text { fill: #111; }
pre code { white-space: pre; }
""".strip()

    return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>{{{{TITLE}}}}</title>
  <style>
/*
  Self-contained LaTeX.css-inspired walkthrough template.
  Source CSS: vendored from https://github.com/vincentdoerig/latex-css
  This file is generated by scripts/build_inline_template.py.
*/
{font_css}

{css}

{extra_css}
  </style>
</head>
<body class=\"text-justify\">
  <header>
    <h1>{{{{TITLE}}}}</h1>
    <p class=\"author\">{{{{AUTHOR}}}}<br />{{{{DATE}}}}</p>
  </header>

  <div class=\"abstract\">
    <h2>Abstract</h2>
    <p>{{{{ABSTRACT}}}}</p>
    <p class=\"keywords\"><strong>Keywords:</strong> {{{{KEYWORDS}}}}</p>
  </div>

  <nav role=\"navigation\" class=\"toc\">
    <h2>Contents</h2>
    <ol>
      <li><a href=\"#section-1\">{{{{SECTION_ONE_TITLE}}}}</a></li>
      <li><a href=\"#section-2\">{{{{SECTION_TWO_TITLE}}}}</a></li>
      <li><a href=\"#section-3\">{{{{SECTION_THREE_TITLE}}}}</a></li>
      <li><a href=\"#section-4\">{{{{SECTION_FOUR_TITLE}}}}</a></li>
      <li><a href=\"#section-5\">{{{{SECTION_FIVE_TITLE}}}}</a></li>
      <li><a href=\"#section-6\">{{{{SECTION_SIX_TITLE}}}}</a></li>
      <li><a href=\"#section-7\">{{{{SECTION_SEVEN_TITLE}}}}</a></li>
      <li><a href=\"#section-8\">{{{{SECTION_EIGHT_TITLE}}}}</a></li>
    </ol>
  </nav>

  <main>
    <article class=\"indent-pars\">
      <section id=\"section-1\">
        <h2>1. {{{{SECTION_ONE_TITLE}}}}</h2>
        <p class=\"no-indent\">{{{{SECTION_ONE_BODY}}}}</p>
      </section>

      <section id=\"section-2\">
        <h2>2. {{{{SECTION_TWO_TITLE}}}}</h2>
        <figure>
          {{{{INLINE_FIGURE_OR_DIAGRAM}}}}
          <figcaption>{{{{FIGURE_CAPTION}}}}</figcaption>
        </figure>
        <p class=\"no-indent\">{{{{SECTION_TWO_BODY}}}}</p>
      </section>

      <section id=\"section-3\">
        <h2>3. {{{{SECTION_THREE_TITLE}}}}</h2>
        <p class=\"no-indent\">{{{{SECTION_THREE_BODY}}}}</p>
      </section>

      <section id=\"section-4\">
        <h2>4. {{{{SECTION_FOUR_TITLE}}}}</h2>
        <table>
          <caption>{{{{TABLE_CAPTION}}}}</caption>
          <thead>
            <tr>
              <th scope=\"col\">{{{{TABLE_HEAD_1}}}}</th>
              <th scope=\"col\">{{{{TABLE_HEAD_2}}}}</th>
              <th scope=\"col\">{{{{TABLE_HEAD_3}}}}</th>
              <th scope=\"col\">{{{{TABLE_HEAD_4}}}}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{{{TABLE_ROW_1_COL_1}}}}</td>
              <td>{{{{TABLE_ROW_1_COL_2}}}}</td>
              <td>{{{{TABLE_ROW_1_COL_3}}}}</td>
              <td>{{{{TABLE_ROW_1_COL_4}}}}</td>
            </tr>
            <tr>
              <td>{{{{TABLE_ROW_2_COL_1}}}}</td>
              <td>{{{{TABLE_ROW_2_COL_2}}}}</td>
              <td>{{{{TABLE_ROW_2_COL_3}}}}</td>
              <td>{{{{TABLE_ROW_2_COL_4}}}}</td>
            </tr>
            <tr>
              <td>{{{{TABLE_ROW_3_COL_1}}}}</td>
              <td>{{{{TABLE_ROW_3_COL_2}}}}</td>
              <td>{{{{TABLE_ROW_3_COL_3}}}}</td>
              <td>{{{{TABLE_ROW_3_COL_4}}}}</td>
            </tr>
          </tbody>
        </table>
        <p class=\"no-indent\">{{{{SECTION_FOUR_BODY}}}}</p>
      </section>

      <section id=\"section-5\">
        <h2>5. {{{{SECTION_FIVE_TITLE}}}}</h2>
        <p class=\"no-indent\">{{{{SECTION_FIVE_BODY}}}}</p>
      </section>

      <section id=\"section-6\">
        <h2>6. {{{{SECTION_SIX_TITLE}}}}</h2>
        <h3><code class=\"break-all\">{{{{SNIPPET_PATH}}}}</code></h3>
        <p class=\"no-indent\">{{{{SNIPPET_WHY}}}}</p>
        <pre><code>{{{{SNIPPET_CODE}}}}</code></pre>
        <p class=\"no-indent\"><strong>Maintenance consequence.</strong> {{{{SNIPPET_CONSEQUENCE}}}}</p>
      </section>

      <section id=\"section-7\">
        <h2>7. {{{{SECTION_SEVEN_TITLE}}}}</h2>
        <p class=\"no-indent\">{{{{SECTION_SEVEN_BODY}}}}</p>
      </section>

      <section id=\"section-8\">
        <h2>8. {{{{SECTION_EIGHT_TITLE}}}}</h2>
        <p class=\"no-indent\">{{{{SECTION_EIGHT_BODY}}}}</p>
        <p class=\"no-indent\"><strong>Where to edit.</strong> {{{{WHERE_TO_EDIT}}}}</p>
        <p class=\"no-indent\"><strong>Caveat.</strong> {{{{CAVEAT}}}}</p>
      </section>
    </article>
  </main>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the fully inline report template.")
    parser.add_argument(
        "--font-set",
        choices=sorted(FONT_SETS.keys()),
        default="minimal",
        help="Which inline font set to embed in the template.",
    )
    args = parser.parse_args()

    TEMPLATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    TEMPLATE_PATH.write_text(build_template(args.font_set))
    print(TEMPLATE_PATH)


if __name__ == "__main__":
    main()
